name: tests

on:
  push:
    branches: [master, main]
    paths-ignore: ['**.md']
    tags-ignore: ['**']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}

      - name: Check for GitLeaks
        uses: gacts/gitleaks@v1 # Action page: <https://github.com/gacts/gitleaks>

  index-docker-image:
    name: Build index docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: docker/build-push-action@v3
        with:
          context: index
          file: index/Dockerfile
          push: false
          tags: image:local

  validate-nomad-manifest:
    name: Validate Nomad manifest
    runs-on: ubuntu-20.04
    steps:
      - uses: gacts/install-nomad@v1

      - uses: actions/checkout@v3

      - run: |
          nomad job validate \
            -var="tg_secret=foo" \
            -var="tg_subdomain=bar" \
            -var="index_page_image=baz" \
              ./deploy/service.hcl
